-- Measurement schema: scales, questions, reports
CREATE TABLE IF NOT EXISTS scales (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  description TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS questions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  scale_id BIGINT NOT NULL,
  seq INT NOT NULL,
  text TEXT NOT NULL,
  max_score INT DEFAULT 4,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (scale_id) REFERENCES scales(id) ON DELETE CASCADE
);

-- reports stores summary and full answers as JSON in details
CREATE TABLE IF NOT EXISTS reports (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  scale_id BIGINT NOT NULL,
  total_score DOUBLE,
  avg_score DOUBLE,
  level VARCHAR(32),
  details JSON,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (scale_id) REFERENCES scales(id) ON DELETE CASCADE
);
